# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default

steps:
- task: Bash@3
  name: bash1
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      export  TEST_NAME1=$TEST_NAME
      
      echo $TEST_NAME1

      cd /home/vsts/work/_tasks
      ls -l
      cd `ls | head -n 1`
      pwd
      ls -l

      cd 3.163.1
      pwd
      ls -l

      cd node_modules
      ls -l

      env

      export TESTER=emas

      echo "##vso[task.setvariable variable=sauce;isOutput=true]crushed tomatoes"

      exit 9

    noProfile: false
    noRc: false
- task: CmdLine@2
  condition: succeededOrFailed()
  continueOnError: true
  inputs:
    script: |
      echo $MY_NAME
      echo $TEST_NAME
      echo $TESTER

      hostname -i

      ifconfig

      echo "----sauce----"
      echo $(bash1.sauce) 

      exit 55
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/examples/build/vue-web/vue'
    Contents: '**'
    TargetFolder: '/home/vsts/work/1/a'